"use client";
import { useState } from "react";
import { Button, Card, Input, Label, Textarea } from "@/components/ui";
import { useRouter } from "next/navigation";
export default function ProfileManager({profiles,users,assignments}:{profiles:any[],users:any[],assignments:any[]}){
 const empty={name:"",email:"",phone:"",location:"",linkedin:"",portfolio:"",target_roles:"",target_locations:"",target_industries:"",skills:"",summary:""};
 const [form,setForm]=useState(empty);const [file,setFile]=useState<File|null>(null);const [editing,setEditing]=useState<string|null>(null);const [assignUser,setAssignUser]=useState<string>("");const [assignProfile,setAssignProfile]=useState<string>("");const [error,setError]=useState("");const router=useRouter();
 async function save(){setError("");const r=await fetch("/api/admin/profiles",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:editing})});const j=await r.json();if(!r.ok){setError(j.error);return;}if(file){const fd=new FormData();fd.append("file",file);fd.append("profile_id",j.id);const rr=await fetch("/api/admin/profiles/resume",{method:"POST",body:fd});const jj=await rr.json();if(!rr.ok){setError(jj.error);return;}}setForm(empty);setFile(null);setEditing(null);router.refresh();}
 async function remove(id:string){if(confirm("Delete this profile? Applications will be preserved.")){await fetch(`/api/admin/profiles/${id}`,{method:"DELETE"});router.refresh();}}
 async function assign(){await fetch("/api/admin/assignments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:assignUser,profile_id:assignProfile})});router.refresh();}
 function edit(p:any){setEditing(p.id);setForm({...empty,...p});window.scrollTo({top:0,behavior:"smooth"});}
 return <><Card className="mb-5"><h2 className="font-bold text-lg mb-4">{editing?"Edit Profile":"Create Profile"}</h2><div className="grid md:grid-cols-2 gap-4">{Object.keys(empty).map(k=><div key={k}><Label>{k.replaceAll("_"," ")}</Label>{["skills","summary"].includes(k)?<Textarea value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<Input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</div>)}<div><Label>Master Resume PDF (max 10 MB)</Label><Input type="file" accept=".pdf,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></div></div>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<div className="flex gap-2 mt-4"><Button onClick={save}>{editing?"Save Changes":"Create Profile"}</Button>{editing&&<Button variant="secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</Button>}</div></Card>
 <Card className="mb-5"><h2 className="font-bold mb-3">Assign Profile</h2><div className="grid md:grid-cols-3 gap-3"><select className="input" value={assignUser} onChange={e=>setAssignUser(e.target.value)}><option value="">Select user</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select><select className="input" value={assignProfile} onChange={e=>setAssignProfile(e.target.value)}><option value="">Select profile</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Button onClick={assign} disabled={!assignUser||!assignProfile}>Assign</Button></div></Card>
 <Card><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Name</th><th>Email</th><th>Location</th><th>Resume</th><th>Actions</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id} className="border-b last:border-0"><td className="py-3 font-semibold">{p.name}</td><td>{p.email}</td><td>{p.location||"—"}</td><td>{p.master_resume_filename?<a className="underline" href={`/api/profiles/${p.id}/resume`}>{p.master_resume_filename}</a>:"Missing"}</td><td className="space-x-2"><button className="underline" onClick={()=>edit(p)}>Edit</button><button className="underline text-red-600" onClick={()=>remove(p.id)}>Delete</button></td></tr>)}</tbody></table></div></Card></>;
}
