"use client";
import { useState } from "react";
import { Button, Card, Input, Label } from "@/components/ui";
import { useRouter } from "next/navigation";
export default function UserManager({users,assignments}:{users:any[],assignments:any[]}){
 const [show,setShow]=useState(false);const [form,setForm]=useState({full_name:"",email:"",password:"",role:"USER"});const [error,setError]=useState("");const router=useRouter();
 async function create(){setError("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)setError(j.error);else{setShow(false);setForm({full_name:"",email:"",password:"",role:"USER"});router.refresh();}}
 async function reset(id:string){const r=await fetch(`/api/admin/users/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reset_access"})});const j=await r.json();if(!r.ok)return alert(j.error);if(j.action_link) navigator.clipboard?.writeText(j.action_link); alert("Recovery link generated and copied when browser permissions allow.");}
 async function toggle(id:string,active:boolean){await fetch(`/api/admin/users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:!active})});router.refresh();}
 async function del(id:string){if(confirm("Disable/delete this user?")){await fetch(`/api/admin/users/${id}`,{method:"DELETE"});router.refresh();}}
 return <><div className="flex justify-end mb-4"><Button onClick={()=>setShow(true)}>Create User</Button></div>{show&&<Card className="mb-5"><div className="grid md:grid-cols-2 gap-4"><div><Label>Full Name</Label><Input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></div><div><Label>Email</Label><Input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Password</Label><Input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div><Label>Role</Label><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>USER</option><option>ADMIN</option></select></div></div>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<div className="flex gap-2 mt-4"><Button onClick={create}>Create</Button><Button variant="secondary" onClick={()=>setShow(false)}>Cancel</Button></div></Card>}
 <Card><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Name</th><th>Email</th><th>Role</th><th>Profiles</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b last:border-0"><td className="py-3">{u.full_name}</td><td>{u.email}</td><td>{u.role}</td><td>{assignments.filter(a=>a.user_id===u.id).map(a=>a.client_profiles?.name).filter(Boolean).join(", ")||"—"}</td><td>{u.is_active?"Active":"Disabled"}</td><td className="space-x-2"><button className="underline" onClick={()=>toggle(u.id,u.is_active)}>{u.is_active?"Disable":"Enable"}</button><button className="underline" onClick={()=>reset(u.id)}>Reset Access</button><button className="underline text-red-600" onClick={()=>del(u.id)}>Delete</button></td></tr>)}</tbody></table></div></Card></>;
}
